### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by 123Lory321** [Dplepler/RedditBot#1]
rip cummylover

**Comment by 123Lory321** [comment]
also you can see the old password from the commit history, you might wanna delete this repo

**Comment by Dplepler** [comment]
Lol I know. I made it a long time ago and committed much later. Stupid
mistake

**Comment by 123Lory321** [comment]
ah ok good, at least i suppose you're not using this password anymore

**Comment by Dplepler** [comment]
I am not, also, how did you find my GitHub?

**Comment by 123Lory321** [comment]
I was searching for cummybot's source and i found this as it contained "cummybot" in the readme
